import type { Metadata } from "next";
import { CartProvider } from "@/components/cart/CartProvider";
import CartLink from "@/components/cart/CartLink";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <CartProvider>
          <nav className="w-full flex justify-end items-center px-6 py-4 bg-white border-b border-gray-200 shadow-sm">
            <ul className="flex gap-6 text-base font-medium items-center">
              <li>
                <Link
                  href="/product"
                  className="transition-colors hover:text-blue-600"
                >
                  Product
                </Link>
              </li>
              <li>
                <CartLink />
              </li>
            </ul>
          </nav>
          <main className="flex-1 min-w-5xl max-w-5xl mx-auto flex flex-col items-stretch bg-white font-sans h-full px-4 py-4">
            {children}
          </main>
        </CartProvider>
      </body>
    </html>
  );
}
